# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(454, 459)
        self.actionGuardar = QAction(MainWindow)
        self.actionGuardar.setObjectName(u"actionGuardar")
        self.actionAbrir = QAction(MainWindow)
        self.actionAbrir.setObjectName(u"actionAbrir")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 0, 181, 411))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 20, 111, 21))
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 50, 111, 21))
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(10, 140, 111, 21))
        self.label_7 = QLabel(self.groupBox)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(10, 80, 111, 21))
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 110, 111, 21))
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(10, 170, 111, 21))
        self.id_lineEdit = QLineEdit(self.groupBox)
        self.id_lineEdit.setObjectName(u"id_lineEdit")
        self.id_lineEdit.setGeometry(QRect(80, 20, 91, 20))
        self.ox_doubleSpinBox = QDoubleSpinBox(self.groupBox)
        self.ox_doubleSpinBox.setObjectName(u"ox_doubleSpinBox")
        self.ox_doubleSpinBox.setGeometry(QRect(80, 50, 91, 22))
        self.ox_doubleSpinBox.setDecimals(0)
        self.ox_doubleSpinBox.setMaximum(500.000000000000000)
        self.oy_doubleSpinBox = QDoubleSpinBox(self.groupBox)
        self.oy_doubleSpinBox.setObjectName(u"oy_doubleSpinBox")
        self.oy_doubleSpinBox.setGeometry(QRect(80, 80, 91, 22))
        self.oy_doubleSpinBox.setDecimals(0)
        self.oy_doubleSpinBox.setMaximum(500.000000000000000)
        self.dx_doubleSpinBox = QDoubleSpinBox(self.groupBox)
        self.dx_doubleSpinBox.setObjectName(u"dx_doubleSpinBox")
        self.dx_doubleSpinBox.setGeometry(QRect(80, 110, 91, 22))
        self.dx_doubleSpinBox.setDecimals(0)
        self.dx_doubleSpinBox.setMaximum(500.000000000000000)
        self.dy_doubleSpinBox = QDoubleSpinBox(self.groupBox)
        self.dy_doubleSpinBox.setObjectName(u"dy_doubleSpinBox")
        self.dy_doubleSpinBox.setGeometry(QRect(80, 140, 91, 22))
        self.dy_doubleSpinBox.setDecimals(0)
        self.dy_doubleSpinBox.setMaximum(500.000000000000000)
        self.vel_lineEdit = QLineEdit(self.groupBox)
        self.vel_lineEdit.setObjectName(u"vel_lineEdit")
        self.vel_lineEdit.setGeometry(QRect(80, 170, 91, 20))
        self.inicio_pushButton = QPushButton(self.groupBox)
        self.inicio_pushButton.setObjectName(u"inicio_pushButton")
        self.inicio_pushButton.setGeometry(QRect(10, 320, 161, 23))
        self.groupBox_2 = QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(-1, 200, 181, 111))
        self.r_doubleSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.r_doubleSpinBox.setObjectName(u"r_doubleSpinBox")
        self.r_doubleSpinBox.setGeometry(QRect(80, 20, 91, 22))
        self.r_doubleSpinBox.setDecimals(0)
        self.r_doubleSpinBox.setMaximum(255.000000000000000)
        self.label_4 = QLabel(self.groupBox_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 20, 47, 20))
        self.g_doubleSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.g_doubleSpinBox.setObjectName(u"g_doubleSpinBox")
        self.g_doubleSpinBox.setGeometry(QRect(80, 50, 91, 22))
        self.g_doubleSpinBox.setDecimals(0)
        self.g_doubleSpinBox.setMaximum(255.000000000000000)
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 50, 47, 21))
        self.b_doubleSpinBox = QDoubleSpinBox(self.groupBox_2)
        self.b_doubleSpinBox.setObjectName(u"b_doubleSpinBox")
        self.b_doubleSpinBox.setGeometry(QRect(80, 80, 91, 22))
        self.b_doubleSpinBox.setDecimals(0)
        self.b_doubleSpinBox.setMaximum(255.000000000000000)
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 80, 47, 16))
        self.final_pushButton = QPushButton(self.groupBox)
        self.final_pushButton.setObjectName(u"final_pushButton")
        self.final_pushButton.setGeometry(QRect(10, 350, 161, 23))
        self.mostrar_pushButton = QPushButton(self.groupBox)
        self.mostrar_pushButton.setObjectName(u"mostrar_pushButton")
        self.mostrar_pushButton.setGeometry(QRect(10, 380, 161, 23))
        self.plainTextEdit = QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(200, 10, 241, 391))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 454, 21))
        self.menuArchivo = QMenu(self.menubar)
        self.menuArchivo.setObjectName(u"menuArchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuArchivo.addAction(self.actionGuardar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionGuardar.setText(QCoreApplication.translate("MainWindow", u"Guardar", None))
#if QT_CONFIG(shortcut)
        self.actionGuardar.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbrir.setText(QCoreApplication.translate("MainWindow", u"Abrir", None))
#if QT_CONFIG(shortcut)
        self.actionAbrir.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Part\u00edcula", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"ID:", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Origen en X:", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"Destino en Y:", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Origen en Y:", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Destino X", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"Velocidad:", None))
        self.inicio_pushButton.setText(QCoreApplication.translate("MainWindow", u"Agregar al inicio", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Color (RGB)", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"R:", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"G:", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"B:", None))
        self.final_pushButton.setText(QCoreApplication.translate("MainWindow", u"Agregar al final", None))
        self.mostrar_pushButton.setText(QCoreApplication.translate("MainWindow", u"Mostrar", None))
        self.menuArchivo.setTitle(QCoreApplication.translate("MainWindow", u"Archivo", None))
    # retranslateUi

